newIssueWelcomeComment: >
  Thank you for opening your first issue here! Be sure to fill out all relevant fields in the issue template!
newPRWelcomeComment: >
  Thanks for making this pull request! Please read through our [contributing guidelines](../CONTRIBUTING.md).
firstPRMergeComment: >
  Congratulations on having your first PR merged! Your improvement is greatly appreciated!
