- id: check-empty
  name: check that specific files are empty
  description: |
    Some marker files such as py.typed and .nojekyll should always be empty, and this
    hook can enforce that. Directories are automatically navigated into if passed.
  entry: check-empty
  language: python
  require_serial: true
  files: '^$'
