- id: check-empty
  name: check that specific files are empty
  description: |
    This hook enforces the emptiness of certain selected marker files. Directories are
    automatically navigated into and each file within scanned similarly if passed, and
    globbing is supported. Refer to the self-documenting metadata file for usage.
  entry: check-empty
  language: python
  require_serial: true
  files: ^$
