name: CI
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  push: {branches: [main]}
  pull_request: {branches: [main]}
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    permissions:
      security-events: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
      with:
        enable-cache: false
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
        ref: ${{github.event.pull_request.head.sha || github.sha}}
    - if: matrix.os == 'ubuntu-latest'
      run: uv audit --preview-features audit-command
    - if: matrix.os == 'ubuntu-latest'
      run: uvx ruff check --output-format github
    - if: matrix.os == 'ubuntu-latest'
      run: uvx ty check --output-format github
    - if: matrix.os == 'ubuntu-latest'
      uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054
    - if: matrix.os == 'ubuntu-latest'
      run: uv build
    - run: uv run --python 3.15 -m test_check_empty
    - run: uv run --python 3.8 -m test_check_empty
    - if: matrix.os != 'windows-latest'
      run: uv run --python pp38 -m test_check_empty
    - run: uv run --python gp312 -m test_check_empty
    timeout-minutes: 3
