name: CI
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  push: {branches: [main]}
  pull_request: {branches: [main]}
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
    - run: uvx ruff check --output-format=github
    - run: uvx ty check --output-format=github
    timeout-minutes: 5
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
    - uses: actions/checkout@v6.0.2
    - run: uv run --python 3.15 -m test_check_empty
    - run: uv run --python 3.8 -m test_check_empty
    - if: matrix.os != 'windows-latest'
      run: uv run --python pp38 -m test_check_empty
    - run: uv run --python gp311 -m test_check_empty
    timeout-minutes: 10
