name: Build and publish
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/check-empty/${{github.ref_name}}
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
      - run: uv build
      - run: uv publish
      - uses: softprops/action-gh-release@v3.0.2
        with:
          discussion_category_name: Releases
          generate_release_notes: true
          prerelease: true
